# Base Info
url: 'https://ltcyber.org'
title: 'Lake Travis Cybersecurity Club'
shortname: 'LT Cyber'
description: 'Cybersecurity Club at Lake Travis High School'
loc: 'Austin, Texas'
year: '2021'
# Social Media
github: 'laketraviscyber'
email: 'hello@ltcyber.org'
lths: 'https://ltisdschools.org/lths'
ltisd: 'https://ltisdschools.org'
