# Base Info
url: 'https://ltcyber.org'
title: 'LT Cyber'
description: 'Cybersecurity Club at Lake Travis High School'
loc: 'Austin, Texas'
year: '2021'
# Social Media
github: 'laketraviscyber'
email: 'laketraviscyber@gmail.com'
lths: 'https://ltisdschools.org/lths'
ltisd: 'https://ltisdschools.org'
